name: CI

on:
  push:
    branches:
    - '**'
    - '!dependabot/**'
  pull_request: {}

env:
  GOPATH: ${{ github.workspace }}
  GO111MODULE: off

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        path: src/github.com/projectriff/bindings
    - uses: actions/setup-go@v1
      with:
        go-version: '1.13'
    - name: Test
      run: go test ./...
      working-directory: src/github.com/projectriff/bindings
